#! /bin/sh
# Script to shut down a network (tap) device for qemu.
# Initially this script is empty, but you can configure,
# for example, accounting info here.

sudo brctl delif br0 $1

sudo tunctl -d $1
 
sudo ifconfig enp0s3 -promisc
sudo ifup enp0s3 

